# Plugin created for the Itsn3w French Community @ www.itsnew.fr
name: TheEndAgain
author: Ribesg
main: com.github.ribesg.tea.TheEndAgain
version: 0.99i
description: Respawn the EnderDragon and/or regen the End world
load: POSTWORLD

commands:
    end:
        description: General End command
        default: op
        usage: |
            /<command> help